version: '3'

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - your_heimdall_config_fold:/config
    ports:
      - 1080:80
    