version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - your_http_server_config_fold:/etc/nginx/conf.d
      - your_static_fold:/usr/share/nginx/html
      - your_log_fold:/var/log/nginx
    network_mode: "host"